name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install huggingface_hub

      - name: Upload to Hugging Face Space
        run: |
          from huggingface_hub import upload_folder
          upload_folder(
            folder_path=".",
            repo_id="Jayanth2323/TCS-Stock-Data-Live-Prediction",
            repo_type="space",
            token="${{ secrets.HF_TOKEN }}"
          )
        shell: python
