name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install DVC (for Hugging Face)
        run: pip install -U dvc[gs]

      - name: Install Hugging Face Hub
        run: pip install huggingface_hub

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "YourName"
          
          # Login to HF
          huggingface-cli login --token $HF_TOKEN

          # Upload to your HF Space repo
          git remote add space https://huggingface.co/spaces/JaKe7389/TCS_Stock_Live_Prediction
          git push space main --force
